CREATE TABLE IF NOT EXISTS customer (
  customer_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(100) NOT NULL,
  password varchar(100) NOT NULL,
  email varchar(100) NOT NULL,
  customer_type varchar(20) NOT NULL,
  created_at date NOT NULL,
  created_by varchar(20) NOT NULL,
  updated_at date DEFAULT NULL,
  updated_by varchar(20) DEFAULT NULL,
  CONSTRAINT UQ_CUSTOMER_USERNAME UNIQUE (username)
);

-- Indexes for customer table
CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_USERNAME_CASE_INSENSITIVE ON customer (LOWER(username));
CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_TYPE_USERNAME ON customer (customer_type, username);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMER_TYPE_ID ON customer (customer_type, customer_id);


CREATE TABLE IF NOT EXISTS invoice (
  customer_id int NOT NULL,
  invoice_number int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_status varchar(50) NOT NULL,
  invoice TEXT NOT NULL,
  created_at date NOT NULL,
  created_by varchar(20) NOT NULL,
  updated_at date DEFAULT NULL,
  updated_by varchar(20) DEFAULT NULL,
  status_last_updated_at date DEFAULT NULL,
  callback varchar(256) DEFAULT NULL,
  correlation_id varchar(100) NOT NULL,
);

-- Indexes for invoice table
CREATE INDEX IF NOT EXISTS IDX_INVOICE_NUMBER ON invoice (invoice_number);
CREATE INDEX IF NOT EXISTS IDX_INVOICE_STATUS_NUMBER ON invoice (invoice_status, invoice_number);
CREATE INDEX IF NOT EXISTS IDX_INVOICE_STATUS ON invoice (invoice_status);
CREATE INDEX IF NOT EXISTS IDX_INVOICE_CREATED_AT ON invoice (created_at);
CREATE INDEX IF NOT EXISTS IDX_INVOICE_STATUS_SENT_AT ON invoice (invoice_status, status_last_updated_at);
CREATE INDEX IF NOT EXISTS IDX_CORRELATION_ID ON invoice (correlation_id);

--
-- Seed data for customer table
--

-- SDI User
INSERT INTO customer (username, password, email, customer_type, created_at, created_by, updated_at, updated_by)
VALUES ('sdi_user', 'sdi_password', 'sdi@governo.it', 'SDI', CURRENT_DATE, 'system', NULL, NULL) ON CONFLICT (username) DO NOTHING;

-- Generic ARUBA test users
INSERT INTO customer (username, password, email, customer_type, created_at, created_by, updated_at, updated_by)
VALUES ('test_user_1', 'aruba_pwd_1', 'test1@aruba.it', 'ARUBA', CURRENT_DATE, 'system', NULL, NULL) ON CONFLICT (username) DO NOTHING;

INSERT INTO customer (username, password, email, customer_type, created_at, created_by, updated_at, updated_by)
VALUES ('test_user_2', 'aruba_pwd_2', 'test2@aruba.it', 'ARUBA', CURRENT_DATE, 'system', NULL, NULL) ON CONFLICT (username) DO NOTHING;

INSERT INTO customer (username, password, email, customer_type, created_at, created_by, updated_at, updated_by)
VALUES ('test_user_3', 'aruba_pwd_3', 'test3@aruba.it', 'ARUBA', CURRENT_DATE, 'system', NULL, NULL) ON CONFLICT (username) DO NOTHING;
