package com.experis.dbmanager.enumerations;

public enum InvoiceStatus {
    INTERNAL_INVOICE_NEW,
    INTERNAL_INVOICE_TOBE_SENT,
    INTERNAL_INVOICE_SENT,
    INTERNAL_INVOICE_NOT_SENT,
    INTERNAL_INVOICE_INVALID,
    INTERNAL_INVOICE_DELIVERED,
    INTERNAL_INVOICE_DISCARDED,
    INTERNAL_INVOICE_NOT_DELIVERED,
    INVOICE_ERROR,
    EXTERNAL_INVOICE

}
