apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmanager-deployment
  labels:
    app: dbmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbmanager
  template:
    metadata:
      labels:
        app: dbmanager
    spec:
      containers:
        - name: dbmanager
          image: giancharlock/dbmanager:s1
          ports:
            - containerPort: 9020
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: prova-invoice-configmap
                  key: DBMANAGER_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: prova-invoice-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: prova-invoice-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: prova-invoice-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: dbmanager
spec:
  selector:
    app: dbmanager
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9020
      targetPort: 9020
